# Generated by Django 2.1.3 on 2020-02-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0002_testresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(verbose_name='状态'),
        ),
    ]
